### ISSUE TITLE
Can't see existing helium account button on certain Android phones

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/maker-starter-app#136]
https://twitter.com/grafiumgroup/status/1519734188785680384?t=-trQIdRE9sqLYRMXILif5w&s=19

https://twitter.com/grafiumgroup/status/1519733820634935302?t=5hC2AdUqLezJudioUDTOEg&s=19

**Comment by Andrewsopoku** [comment]
The users are on an older version of the app. Can we ask ask them to update the app from playstore and see if the issue still persist.

**Comment by shawaj** [comment]
> The users are on an older version of the app. Can we ask ask them to update the app from playstore and see if the issue still persist.

Have done ✅

**Comment by marvinmarnold** [comment]
@posterzh can you see if their issue is resolved now?

**Comment by posterzh** [comment]
That might happen depending how the Helium app is installed. 
It depends if Helium App is installed using Google Play Store App or installed using *.apk file.
Latter case is more error-prone. I will follow @grafiumgroup and trying to reproduce at my side.

**Comment by shawaj** [comment]
Haven't heard back from them. I would close this unless someone else reports it

**Comment by posterzh** [comment]
@shawaj I haven't heard yet from them. But I am almost sure the issue comes from installing the Helium app using *.apk file.
I reproduced the same scenario on my phone.
- My phone is Motorola e.
- When the Helium app is installed from Google Play Store, Nebra app can detect its installation.
- When the Helium app is installed from apk file, Nebra app can't detect its installation.

For the reported issue, the Phone is Huawei and the Google Play Store is not installed on these phones by default.
So I think this issue is related with the Android and Phone model but not the fault of the maker app.

![image](https://user-images.githubusercontent.com/91350131/166564779-77380e05-4adb-4d54-a81a-1358f8780bef.png)

![image](https://user-images.githubusercontent.com/91350131/166563626-fe2de91e-2c5b-4ac2-ad6b-4a31422b6824.png)

**Comment by KevinWassermann94** [comment]
I consider this resolved
