### ISSUE TITLE
Antenna fee is not 0

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#161]
IIRC antenna fee is $0.55

**Acceptance Criteria**
- Show appropriate antenna update fee

**Comment by marvinmarnold** [comment]
@Andrewsopoku can you add a screenshot for @Louisreed to make some adjustments to?

**Comment by Andrewsopoku** [comment]
![Simulator Screen Shot - iPhone 13 - 2022-05-30 at 20 57 26](https://user-images.githubusercontent.com/20680743/171053343-9fe53078-500a-4ad4-b54c-dcf0a5df08b6.png)

**Comment by marvinmarnold** [comment]
@Andrewsopoku can you open a PR for a new release and push to Test Flight?

**Comment by Andrewsopoku** [comment]
@marvinmarnold unexpectedly, i am able to still reproduce the issue when i open antenna update for the first time but the correct fee gets set on subsequent opening. I moved the ticket to in-progress because i am still figuring out what is causing the issue. The easiest fix would be hardcoding the fee since we already know and opening a follow up ticket for a proper fix.

Thoughts?

**Comment by marvinmarnold** [comment]
That sounds good to me. @KevinWassermann94?

**Comment by marvinmarnold** [comment]
Published v1.0.5 to both stores. Waiting on approval.
