### ISSUE TITLE
Implement update hotspot

### ISSUE THREAD

**Issue by posterzh** [NebraLtd/maker-starter-app#48]
**Known issues with the current assert location page:**
1. The current final assert location page is used for 3 purposes:
- Registering Hotspot
- Update Antenna
- Update Location
2. Also, asking BLE permission in runtime is done in the process of registering but not in updating antenna or updating location.

Current final assert location page:
<img src="https://user-images.githubusercontent.com/91350131/158352203-c0430415-966f-4283-a0a0-63a23151373a.png" width="200" />

**Alternative approaches to register hotspot/update antenna/update location:**
Helium Hotspot app use different UI for updating antenna and updating location.
- <img src="https://user-images.githubusercontent.com/91350131/158353187-babf1b19-f984-45ef-9df5-fae4960b49a7.png" width="200" />
- <img src="https://user-images.githubusercontent.com/91350131/158353425-ef5327b9-0a3c-4af6-bc4f-cbeed49b3e87.png" width="200" />

**Possible solutions:**
1. Use same screen to register hotsopt/update antenna/update location.
    Then, we need to update the navigation logic to select the hotspot type, antenna. Checking BLE permission in assert location will be handled automatically in the same way with registering hotspot.
2. Use different screens to register hotsopt/update antenna/update location.
    Then, we need to create a different pages but also need to add checking BLE permission in assert location workflow.

Endpoint: https://docs.helium.com/api/blockchain/accounts#hotspots-for-account

**Acceptance criteria**
- Users must always update location and then antenna, this cannot be done separately.
- BLE connection not required. 
- Nebra only pays for first location assertion
- Option to update visible when viewing a specific hotspot

**Comment by marvinmarnold** [comment]
We have agreed to remove location assertion for now. Can you remove the button @posterzh ?

see: https://nebraltd.slack.com/archives/C024BNQ1Y6T/p1647366524511249

**Comment by marvinmarnold** [comment]
@Louisreed could you come up with mocks for this?

**Comment by marvinmarnold** [comment]
@Louisreed yes. Here are clearer screenshots:

![Screen Shot 2022-03-16 at 10 06 30 AM](https://user-images.githubusercontent.com/1311030/158622646-a9d77fc5-ac31-4bed-ad5e-b436cd9ab7c7.png)
![Screen Shot 2022-03-16 at 10 06 53 AM](https://user-images.githubusercontent.com/1311030/158622649-727447a8-e0d7-415e-9cf0-0d61d34de6f4.png)
![Screen Shot 2022-03-16 at 9 58 38 AM](https://user-images.githubusercontent.com/1311030/158620530-f885bdc0-b228-4bee-a0fe-c23e015b9800.png)
![Uploading Screen Shot 2022-03-16 at 9.58.56 AM.png…](
![Screen Shot 2022-03-16 at 9 59 06 AM](https://user-images.githubusercontent.com/1311030/158620542-c0d1512b-9c0b-4364-86f2-f449785e2220.png)
![Screen Shot 2022-03-16 at 9 59 20 AM](https://user-images.githubusercontent.com/1311030/158620545-d524ba87-ae95-46df-8b40-5493b5d08f31.png)
![Screen Shot 2022-03-16 at 9 59 32 AM](https://user-images.githubusercontent.com/1311030/158620551-2460c32f-669a-4c39-9412-d7d9c6a2d07c.png)
![Screen Shot 2022-03-16 at 9 58 24 AM](https://user-images.githubusercontent.com/1311030/158620517-320ecda3-7f72-4df1-a311-041ffd303b4c.png)

@posterzh @Andrewsopoku can you confirm:
- Which of these screens are already built into maker-starter-app and which we need to build from scratch?
- If it is possible to update the antenna and location in a single transaction. If so, we should combine them so that users don't have to pay twice to update.

**Comment by posterzh** [comment]
@marvinmarnold I will dig into the transaction related with updating antenna and location.

**Comment by Andrewsopoku** [comment]
From my assertion, non of the screens @marvinmarnold shared are in Makerapp although features like "Location Assertion" and "Hotspot Transfer" are present but in a different approach which are not so user friendly.

Depending on whether the team decide to include "Location Assertion" and "Hotspot Transfer";

1. For a users who has linked their wallet but yet to onboard a hotspot can be shown (screen A) as "Home" like we currently do.
2.  Users who have already onboarded hotspot(s) can be shown (screen B), display a list of hotspots associated with the linked wallet. Would the list show only Nebra devices?

3.  Clicking on any hotspot on the list shown on (screen B) would take the user to (screen C) where they can click on "Location Assertion" or "Transfer" of that particular device.

Thoughts?


Screen A
<img height="500" width="auto" src="https://user-images.githubusercontent.com/20680743/158662842-9ac01cd0-ed74-4a77-9280-5979bd6c05f9.PNG"/>


Screen B
<img height="200" width="auto" src="https://user-images.githubusercontent.com/20680743/158664391-44cb72ce-b884-421a-8aa0-ee67909c5a6d.png"/>

Screen C
<img height="300" width="auto" src="https://user-images.githubusercontent.com/20680743/158664595-cbd86650-9ceb-4708-8e6e-50dae4177d09.png"/>

**Comment by posterzh** [comment]
With 2 followup tickets, this can be closed.
- https://github.com/NebraLtd/maker-starter-app/issues/76
- https://github.com/NebraLtd/maker-starter-app/issues/75
