### ISSUE TITLE
Wifi password not being accepted

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#71]
@posterzh can you add some details to this based on https://nebraltd.slack.com/archives/C024BNQ1Y6T/p1648597689707699?thread_ts=1648571588.499249&cid=C024BNQ1Y6T and any open tickets in hm-config?

Related to: Related to: https://github.com/NebraLtd/hm-config/issues/47

**Comment by posterzh** [comment]
Need some style fix.
https://github.com/NebraLtd/maker-starter-app/issues/111

**Comment by posterzh** [comment]
Configuring wifi is implemented differently between "Helium Maker App" and "Helium Hotspots App".
- Helium maker app use [setWifi](https://github.com/NebraLtd/maker-starter-app/blob/4c91377d49fcf1cf85e8a26da21c39c83852fdda/src/features/hotspots/setup/HotspotSetupWifiConnectingScreen.tsx#L67) method from '@helium/react-native-sdk'.
- "Helium Hotspots App" implements the logic of setting up WiFi on [its own](https://github.com/NebraLtd/hotspot-app/blob/86fa04d3e1ae86886309943cffa9fc5fbb32326d/src/utils/useHotspot.ts#L253-L310).

With the `Nebra Indoor` miner that ships the latest `hm-config`, configuring Wifi on Hotspot App doesn't make "Incorrect Password" error but Maker App does. It's because `setWifi()` in the '@helium/react-native-sdk' is implemented a little differently than `setWifiCredentials()` in Hotspots app.

We can fix this WiFi connection issue easily by using the same code in Hotspots App, but technically `hm-config` should be robust enough for both of  `setWifi()` in the '@helium/react-native-sdk' and Hotspot App when configuring WiFi.

**Comment by posterzh** [comment]
We need some improvement on `hm-config` to make configuring WiFi robust later on.
- https://github.com/NebraLtd/hm-config/issues/190
